/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: aUb8rdGMMaGKHrX4GVbzK3

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsdNopCoow8S8C } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: DNopCoow8S8c/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsdNopCoow8S8C
});
