// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicCandidates,
  type DefaultCandidatesProps
} from "./plasmic/applicant_tracking_system/PlasmicCandidates";
import type {HTMLElementRefOf} from "@plasmicapp/react-web";

export interface CandidatesProps extends DefaultCandidatesProps {}

function Candidates_(props: CandidatesProps, ref: HTMLElementRefOf<"div">) {
  return <PlasmicCandidates root={{ ref }} {...props} />;
}

const Candidates = React.forwardRef(Candidates_);
export default Candidates;
