// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicCard,
  type DefaultCardProps
} from "./plasmic/applicant_tracking_system/PlasmicCard";
import type {HTMLElementRefOf} from "@plasmicapp/react-web";

export interface CardProps extends DefaultCardProps {}

function Card_(props: CardProps, ref: HTMLElementRefOf<"div">) {
  return <PlasmicCard root={{ ref }} {...props} />;
}

const Card = React.forwardRef(Card_);
export default Card;
