// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicMetricCard,
  type DefaultMetricCardProps
} from "./plasmic/applicant_tracking_system/PlasmicMetricCard";
import type {HTMLElementRefOf} from "@plasmicapp/react-web";
export interface MetricCardProps extends DefaultMetricCardProps {}

function MetricCard_(props: MetricCardProps, ref: HTMLElementRefOf<"div">) {

  return <PlasmicMetricCard root={{ ref }} {...props} />;
}

const MetricCard = React.forwardRef(MetricCard_);
export default MetricCard;
